add_rules("mode.debug", "mode.release", "mode.releasedbg")
set_languages("c++17")

includes("./src/xmake.lua")

set_rundir("$(projectdir)")

target("cirrus")
    set_kind("binary")
    add_headerfiles("fluid/*.h")
    add_files("fluid/*.cpp", "fluid/*.cu")
    add_includedirs("fluid", {public = true})
    add_cugencodes("native")
    add_cuflags("-extended-lambda --std=c++17")
    --add_cuflags("-rdc=true")
    add_deps("src")

target("tests")
    set_kind("binary")
    add_headerfiles("tests/*.h")
    add_files("tests/*.cpp", "tests/*.cu")
    add_includedirs("tests", {public = true})
    add_cugencodes("native")
    add_cuflags("-extended-lambda --std=c++17 -lineinfo")
    --add_cuflags("-rdc=true")
    add_deps("src")
